<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>blt</string>
	</array>
	<key>name</key>
	<string>Bullet</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(^[ \t]+)?(?=\/\/)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.comment.leading.blt</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?!\G)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\/\/</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.blt</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\n</string>
					<key>name</key>
					<string>comment.line.double-slash.blt</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^[ \t]+)?(?=#)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.comment.leading.blt</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?!\G)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>#</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.blt</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\n</string>
					<key>name</key>
					<string>comment.line.double-slash.blt</string>
				</dict>
			</array>
		</dict>
		<dict>
				<key>match</key>
				<string>.*\[x\].*\n</string>
				<key>name</key>
				<string>comment.line.hidden.blt</string>
		</dict>
		<dict>
				<key>match</key>
				<string>(.*)(@@)[ \t]*(\[-\])</string>
				<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.folded.blt</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment.separator.blt</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.blt</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>@@</string>
			<key>name</key>
			<string>comment.separator.blt</string>
		</dict>
		<dict>
			<key>match</key>
			<string><<</string>
			<key>name</key>
			<string>entity.name.type.link.in.blt</string>
		</dict>
		<dict>
			<key>match</key>
			<string>>></string>
			<key>name</key>
			<string>entity.name.function.link.out.blt</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\[\+\]</string>
			<key>name</key>
			<string>keyword.other.link.blt</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\[\*\]</string>
			<key>name</key>
			<string>variable.other.highlight.blt</string>
		</dict>
		<dict>
			<key>match</key>
			<string>id_\w+</string>
			<key>name</key>
			<string>punctuation.definition.comment.blt</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.blt</string>
</dict>
</plist>