<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>blt</string>
	</array>
	<key>name</key>
	<string>Bullet</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.blt</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other.blt</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.blt</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>named digraph declaration: "digraph NAME {"</string>
			<key>match</key>
			<string> ?(digraph)[ \t]+([A-Za-z0-9]+) ?(\{)</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>edge definition: &lt;- -&gt; --</string>
			<key>match</key>
			<string>(&lt;|-)(&gt;|-)</string>
			<key>name</key>
			<string>keyword.operator.blt</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^[ \t]+)?(?=//)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.comment.leading.blt</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?!\G)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>//</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.blt</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\n</string>
					<key>name</key>
					<string>comment.line.double-slash.blt</string>
				</dict>
			</array>
		</dict>
        <dict>
            <key>match</key>
            <string>.*\[x\].*\n</string>
            <key>name</key>
            <string>comment.line.hidden.blt</string>
        </dict>
        <dict>
            <key>match</key>
            <string>.*\[\*\].*\n</string>
            <key>name</key>
            <string>storage.type.blt</string>
        </dict>
        <dict>
            <key>match</key>
            <string>.*\[-].*\n</string>
            <key>name</key>
            <string>comment.line.folded.blt</string>
        </dict>
	</array>
	<key>scopeName</key>
	<string>source.blt</string>
</dict>
</plist>